# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Ex01:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1

      # Runs a single command using the runners shell
      - name: build
        run: cl /EHsc Ex01.cpp
        
      - name: ls
        run: ls
        
      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: "*.exe"
          retention-days: 4
  teleg:
    needs: Ex01
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
    
      - name: send custom message
        uses: appleboy/telegram-action@master
        with:
          to: 457215938
          token: 1716233084:AAFlbn7JU3y5DfbumLHiQhTc06UAeWgdS10
          message: Ex01_exe
          document: Ex01.exe
